services:
  ftp:
    build:
      context: ./docker
    container_name: lab05-ftp
    environment:
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASSWORD: ${FTP_PASSWORD:?Debe definir FTP_PASSWORD}
      PASV_ADDRESS: ${PASV_ADDRESS:-127.0.0.1}
    ports:
      - "21:21"
      - "40000:40000"
    volumes:
      - ftp-uploads:/srv/ftp/ftpuser/uploads
    restart: unless-stopped

volumes:
  ftp-uploads:
